services:
  web:
    build:
      context: .
      args:
        BUILD_HASH: ${BUILD_HASH:-dev}
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    labels:
      - "dashsync.enable=true"
      - "dashsync.name=DontWordle"
      - "dashsync.group=Websites"
      - "dashsync.url=https://dontwordle.ru"
